services:
  proxy:
    image: sameersbn/squid:latest  # Bruger en pre-konfigureret Squid image
    container_name: squid-proxy
    environment:
      - TZ=Etc/UTC
    networks:
      - internal_network
      - external_network  # Tilføj proxyen til standard bridge-netværket for internetadgang
    ports:
      - "3128:3128"  # Standard Squid port for HTTP proxy
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro  # Mount din egen konfigurationsfil

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    networks:
      - internal_network
      - external_network
    ports:
      - "7860:7860"  # Eksponér port 7860 på hosten
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Din NGINX konfigurationsfil
    depends_on:
      - stable-diffusion-webui
    entrypoint: /bin/sh -c "sleep 10 && nginx -g 'daemon off;'"  # Tilføj en 10 sekunders forsinkelse


  stable-diffusion-webui:
    image: stable-diffusion-webui:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    container_name: sd-webui
    env_file:
      - .env
    environment:
      - HF_HOME=/app/models/CLIP
      - PIP_BREAK_SYSTEM_PACKAGES=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - EGL_PLATFORM=surfaceless
    networks:
      - external_network
    volumes:
      - ./models:/app/models
      - ./outputs:/app/outputs
      - /home/tvup/Projects/stable-diffusion-xl-webui/models/Stable-diffusion/sdxl_vae.safetensors:/app/models/VAE/sdxl_vae.safetensors:ro
      - /home/tvup/Projects/ComfyUI/models/diffusion_models:/app/models/Stable-diffusion:ro
      - /home/tvup/Projects/ComfyUI/models/clip/clip-vit-large-patch14:/app/models/CLIP/clip-vit-large-patch14:ro
      - /home/tvup/Projects/ComfyUI/models/diffusion_models/protovisionXLHighFidelity3D_release0620Bakedvae.safetensors:/app/models/VAE/protovisionXLHighFidelity3D_release0620Bakedvae.safetensors:ro
    shm_size: '20gb'
    gpus: all

networks:
  internal_network:
    driver: bridge
    internal: true
  external_network:
    driver: bridge  # Dette netværk har internetadgang, ikke isoleret

