# squid.conf

# Definer ACL'er for tilladte domæner
#acl allowed_sites dstdomain .github.com .pypi.org .download.pytorch.org .files.pythonhosted.org
acl allowed_sites dstdomain .github.com .huggingface.co .raw.githubusercontent.com cdn-lfs.hf.co

acl localnet src 127.0.0.1/32

# Tillad kun adgang til tilladte domæner og localnet
http_access allow localnet
http_access allow allowed_sites

# Afvis al anden trafik
http_access deny all

# Standard konfigurationer (kan være nødvendigt for at squid kører korrekt)
http_port 3128
coredump_dir /var/spool/squid
